#
# -- Prometheus Alerts --
# Alerts are set manually for each namespace with this command:
# kubectl apply -f helm_deploy/prometheus-alerts.yaml -n laa-apply-for-legalaid-production
#
# you can see current alerts of a namespace with the command:
# kubectl describe prometheusrule -n laa-apply-for-legalaid-production
#
# CloudPlatform has set alerts to be forwarded to slack via the `severity` attribute.
#
#  severity                    | slack channel
#  ---------------------------------------------------
#  apply-for-legal-aid-prod    | #apply-alerts-prod
#  apply-for-legal-aid-staging | #apply-alerts-staging
#  apply-for-legal-aid-uat     | #apply-alerts-uat
#
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: laa-apply-for-legalaid-production
  labels:
    role: alert-rules
  name: prometheus-custom-rules-laa-apply-for-legal-aid
spec:
  groups:
  - name: application-rules
    rules:
    - alert: Instance-Down
      expr: absent(up{namespace="laa-apply-for-legalaid-production"}) == 1
      for: 1m
      labels:
        severity: apply-for-legal-aid-prod
    - alert: Quota-Exceeded
      expr: 100 * kube_resourcequota{job="kube-state-metrics",type="used",namespace="laa-apply-for-legalaid-production"} / ignoring(instance, job, type) (kube_resourcequota{job="kube-state-metrics",type="hard",namespace="laa-apply-for-legalaid-production"} > 0) > 90
      for: 1m
      labels:
        severity: apply-for-legal-aid-prod
      annotations:
        message: Namespace {{ $labels.namespace }} is using {{ printf "%0.0f" $value}}% of its {{ $labels.resource }} quota.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubequotaexceeded
    - alert: NotFound-Threshold-Reached
      expr: sum(rate(ruby_http_requests_total{status="404", namespace="laa-apply-for-legalaid-production"}[86400s])) * 86400 > 100
      for: 1m
      labels:
        severity: apply-for-legal-aid-prod
      annotations:
        message: More than one hundred 404 errors in one day
        runbook_url: https://kibana.apps.cloud-platform-live-0.k8s.integration.dsd.io/_plugin/kibana/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ec9109a0-2b35-11e9-ac82-95e56bd45b02,key:kubernetes.namespace_name,negate:!f,params:(query:laa-apply-for-legalaid-uat,type:phrase),type:phrase,value:laa-apply-for-legalaid-uat),query:(match:(kubernetes.namespace_name:(query:laa-apply-for-legalaid-uat,type:phrase))))),index:ec9109a0-2b35-11e9-ac82-95e56bd45b02,interval:auto,query:(language:lucene,query:'log:%22RoutingError%22'),sort:!('@timestamp',desc))
    - alert: DiskSpace-Threshold-Reached
      expr: container_fs_usage_bytes{namespace="laa-apply-for-legalaid-production"} / 1024 / 1024 > 150 or absent(container_fs_usage_bytes{namespace="laa-apply-for-legalaid-production"})
      for: 1m
      labels:
        severity: apply-for-legal-aid-prod
      annotations:
        message: Container disk space usage is more than 150Mb or is not reported
    - alert: Long-Request
      expr: ruby_http_duration_seconds{namespace="laa-apply-for-legalaid-production"} > 2
      for: 1m
      labels:
        severity: apply-for-legal-aid-prod
      annotations:
        message: Request is taking more than 2 seconds
